### ISSUE TITLE
wiki: pagina Usemssql is incorrect

### ISSUE THREAD

**Issue by mprins** [B3Partners/tailormap-info#1]
De wiki pagina https://github.com/B3Partners/tailormap/wiki/Usemssql is grotendeels incorrect en geen van de links naar de zip files werkt.

Als https://github.com/flamingo-geocms/flamingo/pull/1343 klaar is, is er ondersteuning voor SQL Server 2017

**Comment by cvanlith** [comment]
pagina verwijderd
